[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "modular-coevolution"
version = "2023.6.22"
description="Evolutionary algorithm library focusing on competitive coevolution"
authors = [
    {name = "Sean N. Harris", email = "snh0037@auburn.edu"}
]

requires-python = ">=3.9"
dependencies = []

[project.urls]
Github = "https://github.com/SeanNHarris/modular-coevolution"

[project.optional-dependencies]
alpharank = ["open-spiel", "numpy"]
numba = ["numba", "numpy"]

[tool.setuptools.packages.find]
where = [""]
